---
title: "Lab-7"
author: "Gowri"
format: 
  html:
    embed-resources: true
fig-height: 10
fig-width: 10
editor: visual
---

## 

## **Question 1: How many Sars-Cov-2 papers?**

```{r}
library(rvest)
library(httr)
library(xml2)
library(stringr)

#slide - 32 to 36

# Downloading the website- brackets removed 
website <- xml2::read_html("https://pubmed.ncbi.nlm.nih.gov/?term=sars-cov-2")

# Finding the counts-  slide 33 
#inspect teh webpage to get the orrect Xpath 
#count is in the span or div element with claass "value" or simlar - brackets not needed 
counts <- xml2::xml_find_first(website, "/html/body/main/div[9]/div[2]/div[2]/div[1]/div[1]/h3/span")

# Turning it into text
counts <- as.character(counts)

# Extracting the data using regex- slide 27 
#patterns [0-9,.]+ matches with commas and dots 
#totalcount <- stringr::str_extract(counts, "[REGEX FOR NUMBERS WITH COMMAS/DOTS]")
totalcount <- stringr::str_extract(counts, "[0-9,.]+")

# Removing any commas/dots so that we can convert to numeric- slide 18 to gsub function 
totalcount <- gsub('[,.]', '', totalcount)

#convert to numeric 
totalcount <- as.numeric(totalcount)
print(totalcount)
 
```

\#

## **Question 2: Get article abstracts and authors**

```{r}
# read in text, each line is a separate character- reads the file from downloaded folder 
abstracts <- readLines('~/Downloads/abstract-sars-cov-2-set.txt', warn = FALSE)
# combine all text into one character
abstracts <- paste(abstracts, collapse = '\n')

# split the text whenever 3 new lines occur in a row (indicating two blank lines)
abstracts <- unlist(strsplit(abstracts, split = '\n\n\n'))

# replace any remaining "\n" symbols with spaces
abstracts <- gsub("\n", " ", abstracts)

# replace multiple spaces with single space
abstracts <- gsub(" +", " ", abstracts)

```

## **Question 3: Distribution of universities**

```{r}
library(stringr)
library(stringr)
institution <- str_extract_all(
  abstracts,
  "[A-Z][a-z]+(?:\\s+[A-Z][a-z]+)*\\s+University|insert 2 |insert 3"
  ) 
institution <- unlist(institution)
table(institution)

#university of - my code 
library(stringr)
institution <- str_extract_all(
  abstracts,
  "University of+(?:\\s+[A-Z][a-z])"
  ) 
institution <- unlist(institution)
table(institution)

#university of 
library(stringr)
institution <- str_extract_all(
  abstracts,
  "University\\s+of\\s[A-Z][a-z]+(?:\\s+[A-Z][a-z]+)*|"
  ) 
institution <- unlist(institution)
table(institution)

#...Institute of .....
institution <- str_extract_all(
  abstracts,
  "[A-Z][a-z]+(?:\\s+[A-Z][a-z]+)*\\s+Institute\\s[A-Z][a-z]+| "
  ) 
institution <- unlist(institution)
table(institution)



institution <- str_extract_all(
  abstracts,
  "[A-Z][a-z]+(?:\\s+[A-Z][a-z]+)*\\s+University|
  University\\s+of\\s[A-Z][a-z]+(?:\\s+[A-Z][a-z]+)*|
  [A-Z][a-z]+(?:\\s+[A-Z][a-z]+)*\\s+Institute\\s[A-Z][a-z]+| "
  ) 
institution <- unlist(institution)
table(institution)

#sort - top 10 
sort(table(institution), decreasing = TRUE)[1:10]




```

## **Question 4: Make a tidy dataset**

```{r}
# read in text, each line is a separate character- SLIDE - 32-36- PROCESSING text data  and slide 16-17 - str extract 
#read in text again , keeping line structure for parsing 
abstracts <- readLines('~/Downloads/abstract-sars-cov-2-set.txt', warn = FALSE)
# combine all text into one character
abstracts <- paste(abstracts, collapse = '\n')
# split the text whenever 3 new lines occur in a row (indicating two blank lines)
abstracts <- unlist(strsplit(abstracts, split = '\n\n\n'))

journal <- str_extract(abstracts, "(?<=\\d\\.\\s).*?(?=\\n)")

#extractung titles using str split 
titles <- sapply(abstracts, function(x){
  unlist(strsplit(x, split = "\n\n"))[2]
}, USE.NAMES = FALSE)

authors <- sapply(abstracts, function(x){
  unlist(strsplit(x, split = "\n\n"))[3]
}, USE.NAMES = FALSE)

# slide - 10 - (
#use [\s\s] instead of . to match across newlines 
#*? is non - greedy matching - mslide 9 
#Stop at blank line which is \n followed by \n (double newline)

#Extract authors - third non-empty
affiliations <- str_extract(abstracts, "(?<=Author information:\n)([\\s\\S]*?)(?=\n\n)")

  #combine into dataframe 
papers <- data.frame(
  journal = journal,
   titles = titles,
   authors = authors,
   affiliations = affiliations,
  stringsAsFactors = FALSE
)
knitr::kable(papers[1:5, ])
```
